apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: demo-registry.ap-southeast-5.cr.aliyuncs.com/demo/result:3
        name: result
        ports:
        - containerPort: 80
          name: result
        envFrom:
          - secretRef:
              name: postgres-secret
          - configMapRef:
              name: postgres-cm