apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "DefaultConnection": "Host=db;Username=postgresql;Password=postgresql;Database=postgres;"
      }
    }